---
- hosts: homework_vms
  remote_user: ansible
  become : yes
 
  tasks:
    - name: Update system
      yum:
        name: '*'
        state: latest 
    - name: Install nginx
      yum:
        name: nginx
        state: present
    - name: Install chrony (in centos 8 the ntp package is no longer supported)
      yum:  
        name: chrony
        state: present
    - name: Install mysql
      yum:  
        name: mysql
        state: present 
